---
- name: Install vim
  become: yes
  ansible.builtin.package:
    name: "vim={{ vim_version }}"
    state: present

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: "{{ ansible_facts.env.HOME }}/.vimrc"
